 <?php $posts = $this->getPosts(); ?>
<div class="container">
<div class="col-md-3 blog-content-section blog-mobile-cat">
    <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
			<nav class="blog-subcategory-nav">
                <h3 class="blog-main-title blog-subcategory-nav-title"><?php echo Mage::helper('blog')->__('Categories'); ?></h3>
                <ul class="blog-subcategory-nav-items">
                <?php $cats = $this->getCategories(); ?>
                <?php foreach ($cats as $cat): ?>
                <li class="blog-subcategory-nav-item">
                    <a href="<?php echo $cat->getAddress(); ?>" >
                        <?php echo $cat->getTitle(); ?>
                    </a>
                </li>
                <?php endforeach; ?>
                </ul>
			</nav>
        <?php endif; ?>
    </div>
	<div class="col-md-9 blog-content-section blog-mobile-posts">
<?php if (count($posts)): ?>
 <?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
 
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                <h3><?php echo $post->getCreatedTime(); ?></h3>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> |
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
        </div>
    <?php endforeach; ?>
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php else: ?>
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>
</div>

</div>